### ISSUE TITLE
Error with November Month

### ISSUE THREAD

**Issue by Rexi666** [Artillex-Studios/AxCalendar#1]
When I try to do /rewards, an error come:

[20:48:25 WARN]: java.time.DateTimeException: Invalid date 'NOVEMBER 31'
[20:48:25 WARN]:        at java.base/java.time.LocalDate.create(LocalDate.java:461)
[20:48:25 WARN]:        at java.base/java.time.LocalDate.of(LocalDate.java:273)
[20:48:25 WARN]:        at java.base/java.time.LocalDate.withDayOfMonth(LocalDate.java:1124)
[20:48:25 WARN]:        at java.base/java.time.LocalDateTime.withDayOfMonth(LocalDateTime.java:1020)
[20:48:25 WARN]:        at java.base/java.time.ZonedDateTime.withDayOfMonth(ZonedDateTime.java:1381)
[20:48:25 WARN]:        at AxCalendar-1.8.1.jar//com.artillexstudios.axcalendar.utils.CalendarUtils.getMilisUntilDay(CalendarUtils.java:48)
[20:48:25 WARN]:        at AxCalendar-1.8.1.jar//com.artillexstudios.axcalendar.gui.impl.CalendarGui.open(CalendarGui.java:64)
[20:48:25 WARN]:        at AxCalendar-1.8.1.jar//com.artillexstudios.axcalendar.commands.subcommands.SubCommandOpen.subCommand(SubCommandOpen.java:10)
[20:48:25 WARN]:        at AxCalendar-1.8.1.jar//com.artillexstudios.axcalendar.commands.Commands.open(Commands.java:38)

on the Config, I had November as the month, then I updated the plugin and now I have "AUTO", but the plugin still dont work.

I algo tried with /papi parse to see the day and month of the server but its ok

**Comment by BenceX100** [comment]
You probably have 31 days set up and november only has 30 days
